version: 2.1

jobs:
  create_infrastructure:  # 1st build
    docker:
      - image: amazon/aws-cli  # image user=root, default working dir=/root/project 
    steps:
      - checkout  # check out source code to working directory
      # - run:
      #     name: "Create Cloudformation Stack"
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file cloudformation_template.yml \
      #         --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
      #         --region ${AWS_DEFAULT_REGION}
      - run:
          name: get created ec2 instance public ip
          command: |
            echo "[all]" > inventory
            aws ec2 describe-instances  \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> inventory
            cat inventory
            mv inventory /tmp/inventory  # save_dir == restore_dir
      - save_cache:
          key: instance-inventory
          paths:
            - /tmp/inventory

  configure_infrastructure:  # 2nd build
    docker:
      - image: circleci/python  # image user=circleci, default working dir=/home/circleci/project
    steps:
      - checkout  # check out source code to working directory
      - add_ssh_keys:  # using EC2 instance ssh key
          fingerprints:
            - "8c:ce:93:49:43:3e:24:b0:7d:4f:10:77:9f:c1:05:77"
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install ansible
      - restore_cache:
          keys:
            - instance-inventory
      - run:
          name: Run Playbook and Configure server
          command: |
            sudo cp /tmp/inventory .
            cat inventory
            ansible-playbook ansible-main.yml

workflows:
  ci-cd-workflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires:
            - create_infrastructure
